// apps/base-mobile/src/components/inputs/SelectInput.tsx
import { useEffect, useMemo, useState } from 'react'
import { Pressable, Text } from 'react-native'
import { BaseInput } from './BaseInput'
import type { FormInputComponentProps, SelectOption } from './types'
import { Icon, Popover } from '../base'
import { materialColors } from '../../theme/material'
import { api } from '../../lib/api'

const EMPTY_OPTIONS: SelectOption[] = []
const EMPTY_PARAMS: Record<string, any> = {}
const NOOP_ON_SELECT = () => undefined

async function defaultSelectGetData(getAPI: string, searchParameters: Record<string, any>) {
  const response = await api.dataset(getAPI, { ...(searchParameters || {}) })
  if (Array.isArray(response?.data)) return response.data
  if (Array.isArray(response)) return response
  return []
}

function isNil(value: unknown): value is null | undefined {
  return value === null || value === undefined
}

export function SelectInput({
  field,
  label,
  value,
  onChangeValue,
  onValidationTouch,
  helperMessage,
  enableHelperMessage,
  error,
  disabled = false,
  placeholder = 'Pilih',
  data,
  getAPI = '',
  searchParameters,
  getData,
  defaultToFirst = false,
  pick = 'id',
  view = 'name',
  multi = false,
  asWhole = false,
  transform,
  onSelect,
  clearable = true,
}: FormInputComponentProps) {
  const resolvedData = data ?? EMPTY_OPTIONS
  const resolvedSearchParameters = searchParameters ?? EMPTY_PARAMS
  const resolvedGetData = getData ?? defaultSelectGetData
  const resolvedOnSelect = onSelect ?? NOOP_ON_SELECT

  const [options, setOptions] = useState<SelectOption[]>([])
  const [selected, setSelected] = useState<SelectOption | SelectOption[] | null>(multi ? [] : null)
  const [open, setOpen] = useState(false)

  function isSameValue(left: unknown, right: unknown): boolean {
    if (left === right) return true
    if ((isNil(left) && right === '') || (left === '' && isNil(right))) return true

    const leftIsObject = left != null && typeof left === 'object'
    const rightIsObject = right != null && typeof right === 'object'

    if (leftIsObject || rightIsObject) {
      const leftPicked = leftIsObject ? (left as Record<string, any>)?.[pick] : left
      const rightPicked = rightIsObject ? (right as Record<string, any>)?.[pick] : right
      return String(leftPicked) === String(rightPicked)
    }

    return String(left) === String(right)
  }

  function getCurrentPicked() {
    if (multi) return null
    if (asWhole && value && typeof value === 'object') {
      return (value as Record<string, any>)[pick]
    }
    return value
  }

  function pickSelected(nextOptions: SelectOption[], currentValue: unknown) {
    if (multi) {
      if (Array.isArray(currentValue) && currentValue.length > 0) {
        return nextOptions.filter((item) =>
          currentValue.find(
            (modelItem: any) => String((modelItem && typeof modelItem === 'object' ? modelItem[pick] : modelItem)) === String(item[pick])
          )
        )
      }
      return defaultToFirst && nextOptions[0] ? [nextOptions[0]] : []
    }

    if (currentValue) {
      if (asWhole && typeof currentValue === 'object') {
        return nextOptions.find((item) => String(item[pick]) === String((currentValue as any)?.[pick])) || null
      }
      return nextOptions.find((item) => String(item[pick]) === String(currentValue)) || null
    }

    return defaultToFirst && nextOptions[0] ? nextOptions[0] : null
  }

  function updateModelValue(nextSelected: SelectOption | SelectOption[] | null) {
    if (multi) {
      const currentValue = Array.isArray(value) ? value : []
      const selectedArray = Array.isArray(nextSelected) ? nextSelected : []

      const nextValue = selectedArray.map((item) => {
        const correspondingValue = currentValue.find((modelItem: any) => {
          const modelPick = typeof modelItem === 'object' ? modelItem?.[pick] : modelItem
          return String(modelPick) === String(item[pick])
        })
        if (correspondingValue) return correspondingValue
        return item
      })

      const mappedCurrent = currentValue.map((item: any) => (typeof item === 'object' ? item?.[pick] : item))
      const mappedNext = nextValue.map((item: any) => (typeof item === 'object' ? item?.[pick] : item))

      if (JSON.stringify(mappedCurrent) !== JSON.stringify(mappedNext)) {
        onChangeValue(nextValue)
      }

      resolvedOnSelect(selectedArray)
      return
    }

    const nextValue = asWhole ? nextSelected : (nextSelected as any)?.[pick]

    if (!isSameValue(value, nextValue)) {
      onChangeValue(nextValue)
    }

    resolvedOnSelect(nextSelected as SelectOption | null)
  }

  useEffect(() => {
    if (value != null) return
    if (!multi) return

    onChangeValue([])
    setSelected([])
  }, [multi, onChangeValue, value])

  useEffect(() => {
    let cancelled = false

    async function loadOptions() {
      const loaded = getAPI ? await resolvedGetData(getAPI, resolvedSearchParameters) : resolvedData
      const normalized = Array.isArray(loaded) ? loaded : Array.isArray((loaded as any)?.data) ? (loaded as any).data : []

      let nextOptions = normalized
      if (transform) {
        const transformedData = JSON.parse(JSON.stringify(normalized))
        const transformEntries = Object.entries(transform)
        transformedData.forEach((item: Record<string, any>) => {
          transformEntries.forEach(([sourceKey, targetKey]) => {
            item[targetKey] = item[sourceKey]
            delete item[sourceKey]
          })
        })
        nextOptions = transformedData
      }

      if (cancelled) return

      setOptions(nextOptions)

      const hadValue = value != null && (Array.isArray(value) ? value.length > 0 : true)
      const nextSelected = pickSelected(nextOptions, value)
      setSelected(nextSelected)

      if (!hadValue || multi) {
        updateModelValue(nextSelected)
      }
    }

    void loadOptions()

    return () => {
      cancelled = true
    }
  }, [resolvedData, getAPI, resolvedGetData, multi, pick, resolvedSearchParameters, transform, value, asWhole, defaultToFirst])

  useEffect(() => {
    setSelected(pickSelected(options, value))
  }, [asWhole, defaultToFirst, multi, options, pick, value])

  const displayValue = useMemo(() => {
    if (multi) {
      const selectedItems = Array.isArray(selected) ? selected : []
      if (!selectedItems.length) return ''

      const joined = selectedItems
        .slice(0, 2)
        .map((item) => String(item?.[view] ?? ''))
        .join(', ')

      if (selectedItems.length > 2) {
        return `${joined}, dan ${selectedItems.length - 2} lainnya`
      }

      return joined
    }

    if (selected != null && typeof selected === 'object' && !Array.isArray(selected)) {
      return String((selected as Record<string, any>)?.[view] ?? '')
    }

    return ''
  }, [multi, selected, view])

  function isSelected(item: SelectOption) {
    if (multi) {
      const selectedItems = Array.isArray(selected) ? selected : []
      return selectedItems.map((selectedItem) => selectedItem[pick]).includes(item[pick])
    }

    return String(getCurrentPicked()) === String(item[pick])
  }

  function handleItemPress(item: SelectOption, handleValidationTouch: () => void) {
    if (disabled) return

    if (!multi) {
      setSelected(item)
      setOpen(false)
      updateModelValue(item)
      handleValidationTouch()
      return
    }

    const currentSelected = Array.isArray(selected) ? selected : []
    const nextSelected = currentSelected.map((selectedItem) => selectedItem[pick]).includes(item[pick])
      ? currentSelected.filter((selectedItem) => selectedItem[pick] !== item[pick])
      : [...currentSelected, item]

    setSelected(nextSelected)
    updateModelValue(nextSelected)
    handleValidationTouch()
  }

  function handleClear(handleValidationTouch: () => void) {
    if (disabled) return

    if (!multi) {
      setSelected(null)
      setOpen(false)
      onChangeValue(null)
    } else {
      setSelected([])
      onChangeValue(null)
    }

    handleValidationTouch()
  }

  const showClearAction = !disabled && clearable && Boolean(value)

  return (
    <BaseInput
      field={field}
      label={label}
      error={error}
      helperMessage={helperMessage}
      enableHelperMessage={enableHelperMessage ?? false}
      onValidationTouch={onValidationTouch}
    >
      {({ onValidationTouch: handleValidationTouch }) => (
        <Popover
          disabled={disabled}
          open={open}
          onOpenChange={setOpen}
          side="bottom"
          align="start"
          width="full"
          maxHeight={320}
          contentContainerStyle={{
            borderRadius: 12,
            borderWidth: 1,
            borderColor: materialColors.outlineVariant,
            backgroundColor: materialColors.surfaceContainer,
          }}
        >
          <Popover.Trigger>
            <Pressable
              accessibilityRole="button"
              accessibilityLabel={label || field}
              accessibilityState={{ disabled, expanded: open }}
              disabled={disabled}
              onPress={() => setOpen(true)}
              className="w-full flex-row items-center gap-2 rounded-lg px-4 py-3"
              style={{
                borderWidth: 1,
                borderColor: materialColors.outlineVariant,
                backgroundColor: disabled ? materialColors.surfaceContainerHigh : undefined,
                opacity: disabled ? 0.65 : 1,
              }}
            >
              {displayValue ? (
                <Text numberOfLines={1} className="flex-1" style={{ color: materialColors.onSurface }}>
                  {displayValue}
                </Text>
              ) : (
                <Text numberOfLines={1} className="flex-1" style={{ color: materialColors.onSurfaceVariant }}>
                  {placeholder}
                </Text>
              )}

              {showClearAction ? (
                <Pressable
                  accessibilityRole="button"
                  accessibilityLabel={`${field}-clear`}
                  onPress={(event) => {
                    event?.stopPropagation?.()
                    handleClear(handleValidationTouch)
                  }}
                >
                  <Icon name="close" />
                </Pressable>
              ) : (
                <Icon accessibilityLabel={`${field}-arrow`} name="arrow-down-s" />
              )}
            </Pressable>
          </Popover.Trigger>

          <Popover.Content>
            {options.length ? (
              options.map((item, index) => {
                const itemLabel = String(item?.[view] ?? '')
                const selectedItem = isSelected(item)

                return (
                  <Pressable
                    key={`${String(item?.[pick] ?? index)}-${index}`}
                    testID={`select-option-${field}-${index}`}
                    onPress={() => handleItemPress(item, handleValidationTouch)}
                    className="flex-row items-center justify-between gap-3 px-3 py-2"
                    style={{
                      backgroundColor: materialColors.surfaceContainer,
                    }}
                  >
                    <Text className="flex-1" style={{ color: materialColors.onSurface }}>
                      {itemLabel}
                    </Text>
                    <Icon name="check" style={{ opacity: selectedItem ? 1 : 0 }} />
                  </Pressable>
                )
              })
            ) : (
              <Text className="px-2 py-1 text-xs" style={{ color: materialColors.onSurfaceVariant }}>
                Tidak ada data
              </Text>
            )}
          </Popover.Content>
        </Popover>
      )}
    </BaseInput>
  )
}

export type { FormInputComponentProps as FormSelectInputProps }

// packages/vue-framework/src/components/inputs/SelectInput.vue
<script setup lang="ts">
import { defaultGetData } from '@repo/vue-framework/behaviors/select'
import { ref, type PropType, watch, computed, type ComputedRef, onMounted } from 'vue'
import { commonProps } from './commonprops'
import BaseInput from './BaseInput.vue'
import Popover from '@repo/vue-framework/components/base/Popover.vue'
import TextInput from '@repo/vue-framework/components/inputs/TextInput.vue'

const props = defineProps({
  placeholder: {
    type: String,
    required: false,
    default: 'Pilih',
  },
  data: {
    type: Array as PropType<Array<Record<string, string>>>,
    required: false,
    default: [],
  },
  getAPI: {
    type: String,
    required: false,
    default: '',
  },
  searchParameters: {
    type: Object as PropType<Record<string, string>>,
    required: false,
    default: {},
  },
  getData: {
    type: Function as PropType<(getAPI: string, searchParameters: object) => Promise<Array<any>>>,
    required: false,
    default: defaultGetData,
  },
  defaultToFirst: {
    type: Boolean,
    required: false,
    default: false,
  },
  pick: {
    type: String,
    required: false,
    default: 'id',
  },
  view: {
    type: String,
    required: false,
    default: 'name',
  },
  multi: {
    type: Boolean,
    required: false,
    default: false,
  },
  searchable: {
    type: Boolean,
    required: false,
    default: true,
  },
  asWhole: {
    type: Boolean,
    required: false,
    default: false,
  },
  transform: {
    type: Object,
  },
  onSelect: {
    type: Function,
    default: () => {},
  },
  clearable: {
    type: Boolean,
    required: false,
    default: true,
  },
  ...commonProps,
})

const modelValue = defineModel<any[] | Record<string, string> | null | string>()
const emit = defineEmits<{
  (event: 'validation:touch'): void
}>()

const loading = ref(true)
const data = ref<Array<any>>([])
const query = ref('')
const selected = ref<any[] | Record<string, string> | null>()

onMounted(() => {
  if (modelValue.value != null) return
  if (props.multi) {
    modelValue.value = []
    selected.value = []
  }
})

let displayValue: ComputedRef<string>
const filteredData = computed(() => {
  if (query.value) return data.value.filter((item: any) => item[props.view].toLowerCase().includes(query.value.toLowerCase()))
  else return data.value
})

function isSameValue(a: any, b: any) {
  if (a === b) return true
  if ((a == null && b === '') || (a === '' && b == null)) return true

  const aIsObject = a != null && typeof a === 'object'
  const bIsObject = b != null && typeof b === 'object'

  // For object values (asWhole mode), compare by picked key to avoid
  // false positives like String({}) === String({}) => "[object Object]".
  if (aIsObject || bIsObject) {
    const aPicked = aIsObject ? (a as any)?.[props.pick] : a
    const bPicked = bIsObject ? (b as any)?.[props.pick] : b
    return String(aPicked) === String(bPicked)
  }

  return String(a) === String(b)
}

const currentPicked = computed(() => {
  if (props.multi) return null
  if (props.asWhole && modelValue.value && typeof modelValue.value === 'object') {
    return (modelValue.value as any)[props.pick]
  }
  return modelValue.value as any
})

function pickSelected() {
  if (Array.isArray(modelValue.value)) {
    if (modelValue.value?.length)
      (selected.value as any[]) = data.value.filter((item: any) => (modelValue.value as any[]).find((modelItem: any) => String(modelItem[props.pick]) === String(item[props.pick])))
    else selected.value = props.defaultToFirst ? [data.value[0]] : []
  } else {
    if (modelValue.value) {
      if (props.asWhole && typeof modelValue.value === 'object') {
        selected.value = data.value.find((item: any) => String(item[props.pick]) === String((modelValue.value as any)?.[props.pick]))
      } else {
        selected.value = data.value.find((item: any) => String(item[props.pick]) === String(modelValue.value))
      }
    } else {
      selected.value = props.defaultToFirst ? data.value[0] : null
    }
  }
}

displayValue = computed(() => {
  if (props.multi) {
    if (selected.value?.length)
      return (
        (selected.value as any[])
          .slice(0, 2)
          .map((item) => item[props.view])
          .join(', ') + ((selected.value as any[]).length > 2 ? `, dan ${(selected.value as any[]).length - 2} lainnya` : '')
      )
    else return ''
  } else {
    if (selected.value != null) return (selected.value as any)[props.view]
    else return ''
  }
})

async function preflight() {
  if (props.getAPI) data.value = await props.getData(props.getAPI, props.searchParameters)
  else data.value = props.data
  if (props.transform) {
    const transformedData = JSON.parse(JSON.stringify(data.value))
    const entries = Object.entries(props.transform)
    transformedData.forEach((item: any) => {
      entries.forEach((entry) => {
        item[entry[1]] = item[entry[0]]
        delete item[entry[0]]
      })
    })
    data.value = transformedData
  }

  const hadValue = modelValue.value != null && (Array.isArray(modelValue.value) ? modelValue.value.length > 0 : true)
  pickSelected()
  loading.value = false

  // Only update modelValue if we're setting a default (no existing value) or if multi-select
  if (!hadValue || props.multi) {
    updateModelValue()
  }
}

function updateModelValue() {
  let nextValue: any

  if (props.multi && Array.isArray(modelValue.value)) {
    nextValue = (selected.value as any[])?.map((item: any) => {
      const correspondingValue = (modelValue.value as any[])?.find((mv) => mv[props.pick] === item[props.pick])
      if (correspondingValue) return correspondingValue
      else return item
    })
  } else {
    nextValue = props.asWhole ? (selected.value as any) : (selected.value as any)?.[props.pick]
  }

  if (props.multi) {
    const currentValue = Array.isArray(modelValue.value) ? modelValue.value : []
    const mappedCurrent = currentValue.map((item: any) => (typeof item === 'object' ? item?.[props.pick] : item))
    const mappedNext = Array.isArray(nextValue) ? nextValue.map((item: any) => (typeof item === 'object' ? item?.[props.pick] : item)) : []

    if (JSON.stringify(mappedCurrent) !== JSON.stringify(mappedNext)) {
      modelValue.value = nextValue
    }
  } else if (!isSameValue(modelValue.value, nextValue)) {
    modelValue.value = nextValue
  }

  props.onSelect(selected.value)
}

function handleItemClick(item: any, setOpen: Function) {
  if (item == null) {
    if (!props.multi) {
      selected.value = null
      setOpen(false)
    } else {
      selected.value = []
    }
    // updateModelValue()
    modelValue.value = null
    emit('validation:touch')
    return
  }
  if (!props.multi) {
    selected.value = item
    setOpen(false)
  } else {
    // Ensure selected is an array for multi-select
    const currentSelected = Array.isArray(selected.value) ? selected.value : []
    if (currentSelected.map((s: any) => s[props.pick]).includes(item[props.pick])) {
      selected.value = currentSelected.filter((selectedItem: any) => selectedItem[props.pick] !== item[props.pick])
    } else {
      selected.value = [...currentSelected, item]
    }
  }
  updateModelValue()
  emit('validation:touch')
}

preflight()

onMounted(() => {
  watch(modelValue, () => {
    pickSelected()
  })
})
</script>

<template>
  <BaseInput v-bind="props">
    <div class="w-full min-w-0 max-w-full">
      <Popover :class="$attrs.class" :disabled="disabled">
        <template #trigger>
          <div
            :key="`${String(displayValue)}`"
            :class="`flex w-full min-w-0 max-w-full flex-row items-center justify-between gap-2 overflow-hidden rounded-lg bg-surface-container px-4 py-2 outline outline-1 outline-outline/[24%] ${
              disabled ? 'pointer-events-none cursor-not-allowed !bg-surface-variant/50 ' : ''
            } ${$attrs.class || ''}`"
          >
            <p v-if="displayValue" class="min-w-0 max-w-full flex-1 truncate text-start">{{ displayValue }}</p>
            <p v-else class="text-muted">{{ placeholder }}</p>
            <Icon v-if="disabled || !modelValue || !clearable" name="arrow-down-s" />
            <button v-else-if="clearable" @click="() => handleItemClick(null, () => {})" class="flex items-center justify-center">
              <Icon name="close" />
            </button>
          </div>
        </template>
        <template #content="{ setOpen }">
          <Card class="max-h-80 max-w-screen-sm gap-1 bg-surface-container-high p-0 shadow-sm" variant="outlined">
            <div v-if="props.searchable" class="sticky top-0 z-10 border-b border-outline-variant bg-surface-container-high p-4">
              <TextInput disable-helper-message v-model="query" placeholder="Cari..." icon="search" />
            </div>
            <div v-if="filteredData.length" class="h-full overflow-y-auto p-4">
              <Card v-for="item in filteredData" color="surface-high" interactive class="flex flex-row items-center justify-between gap-4 px-4 py-2" @click="() => handleItemClick(item, setOpen)">
                <div class="">{{ item[view] }}</div>
                <Icon v-if="multi && Array.isArray(modelValue)" :class="modelValue.map((item) => item[pick]).includes(item[pick]) ? 'opacity-100' : 'opacity-0'" name="check"></Icon>
                <Icon v-else :class="String(currentPicked) === String(item[pick]) ? 'opacity-100' : 'opacity-0'" name="check"></Icon>
              </Card>
            </div>
            <p v-else class="p-2 text-xs text-muted">Tidak ada data</p>
          </Card>
        </template>
      </Popover>
    </div>
  </BaseInput>
</template>
