// src/components/composites/CRUD/CRUDCreate.vue
<script setup lang="ts">
import { toast } from 'vue-sonner'
import Form from '../Form.vue'
import { useRoute, useRouter } from 'vue-router'
import { bulkCreateFormProps, composeInputTemplateSheet } from '@/app/actions/CRUD/CRUDCreate'
import Modal from '@/components/base/Modal.vue'
import { defaultFormConfig } from '@/app/configs/_defaults'
import { defineAsyncComponent } from 'vue'

const props = defineProps<{
  config: CRUDCompositeConfig
  permissions: CRUDPermissions
}>()

const [route, router] = [useRoute(), useRouter()]

if (!props.config.title) props.config.title = String(route.meta.title)

const createFormConfig: CreateConfig = {
  fields: props.config.transaction?.create?.fields || props.config.transaction?.fields || props.config.fields || [],
  targetAPI: props.config.transaction?.create?.targetAPI || props.config.transaction?.targetAPI || props.config.name,
  fieldsAlias: { ...defaultFormConfig.fieldsAlias, ...(props.config.transaction?.create?.fieldsAlias || props.config.transaction?.fieldsAlias || props.config.fieldsAlias) },
  inputConfig: props.config.transaction?.create?.inputConfig || props.config.transaction?.inputConfig,
  extraData: props.config.transaction?.create?.extraData || props.config.transaction?.extraData,
  getInitialData: props.config.transaction?.create?.getInitialData || props.config.transaction?.getInitialData,
  onSuccess: props.config.transaction?.create?.onSuccess,
}
</script>

<template>
  <div class="flex flex-col gap-2">
    <slot v-if="$slots['create-header']" name="create-header"></slot>
    <Card v-else class="flex flex-row items-center justify-between gap-4">
      <div class="flex flex-row items-center gap-4">
        <Button
          @click="() => ($route.query['redirected'] == 'true' ? $router.back() : $router.push({ query: { ...$route.query, [`${config.name}_view`]: 'list' } }))"
          variant="icon"
          size="square"
          class="max-w-fit"
        >
          <Icon name="arrow-left" />
        </Button>
        <div class="min-w-max text-xl">Tambah {{ config.title || $route.meta.title }}</div>
      </div>
      <!-- <Modal>
        <template #trigger>
          <Button variant="icon"><Icon name="function-add"></Icon>Bulk Create</Button>
        </template>
        <template #title>
          Bulk Create
        </template>
        <template #content>
          <div class="flex flex-col gap-4">
            <ol class="list-decimal ml-4">
              <li><span class="italic">Download</span> file template <button class="inline-flex text-info" @click="() => composeInputTemplateSheet(createFormConfig)">di sini <Icon class="ml-1" size="md" name="download"></Icon></button></li>
              <li><span class="italic">Upload file template</span> yang sudah terisi di bawah ini</li>
              <li>Tekan <span class="italic font-semibold">submit</span></li>
            </ol>
            <Form
              :fields="['data']"
              :fieldsAlias="{
                data: 'Data'
              }"
              :inputConfig="{
                data: {
                  type: 'custom',
                  component: defineAsyncComponent(() => import('@/components/composites/CRUD/_layouts/SpreadsheetReader.vue')) as any,
                  props: {
                    fields: createFormConfig.fields
                  }
                }
              }"
              :targetAPI="`${createFormConfig.targetAPI}/bulk-create?custom`"
              :onSuccess="createFormConfig.onSuccess ? createFormConfig.onSuccess : () => {
                toast.success('Berhasil menambahkan data!')
                $router.back()
              }"
            />
          </div>
        </template>
      </Modal> -->
    </Card>
    <Transition name="vfade" mode="out-in">
      <Suspense>
        <template #fallback>
          <div class="flex w-full items-center justify-center">
            <Spinner />
          </div>
        </template>
        <slot v-if="$slots['create-main']" name="create-main" />
        <Card v-else>
          <Form
            v-bind="(createFormConfig as any)"
            formType="create"
            :onSuccess="
              createFormConfig.onSuccess
                ? createFormConfig.onSuccess
                : () => {
                    toast.success('Berhasil menambahkan data!')
                    $router.back()
                  }
            "
          />
        </Card>
      </Suspense>
    </Transition>
  </div>
</template>

// apps/mobile/src/components/composites/CRUD/CRUDCreate.tsx
import { useMemo } from 'react'
import { Text, View } from 'react-native'
import { buildFormConfig } from '@repo/model-meta'
import { Form } from '../Form'
import Icon from 'react-native-remix-icon'
import { materialColors } from '@/theme/material'
import { Button } from '../../base'
import type { MobileModelConfig } from '../../../features/routes/catalog.types'

type CRUDCreateProps = {
  config: MobileModelConfig
  onBack: () => void
}

export function CRUDCreate({ config, onBack }: CRUDCreateProps) {
  const createConfig = useMemo(() => buildFormConfig(config, 'create'), [config])

  return (
    <View className="gap-3">
      <View className="flex-row items-center justify-between" style={{ columnGap: 8 }}>
        <Button variant="outlined" color="secondary" size="square" onPress={onBack}>
          <Icon name="arrow-left-s-line" size={24} color={materialColors.onSurface} fallback={null} />
        </Button>
      </View>
      <View className="flex-row items-center justify-between">
        <Text className="text-base font-semibold text-text">Tambah {config.title}</Text>
      </View>
      <Form
        formType="create"
        fields={createConfig.fields || []}
        inputConfig={createConfig.inputConfig}
        fieldsAlias={createConfig.fieldsAlias}
        targetAPI={createConfig.targetAPI || config.name}
        extraData={createConfig.extraData}
        getInitialData={createConfig.getInitialData}
        onSuccess={() => onBack()}
      />
    </View>
  )
}
