// src/components/inputs/BaseInput.vue
<script setup lang="ts">
import { hasRequiredValidation, type ValidationRule } from '@/app/actions/validations'
import { computed, inject, ref, type Ref } from 'vue'
import { twMerge } from 'tailwind-merge'

type FormValidationContext = {
  formData: Ref<Record<string, any>>
  fieldErrors: Ref<Record<string, string>>
  fieldTouched: Ref<Record<string, boolean>>
  submitAttempted: Ref<boolean>
  validateField: (field: string) => string
  validateVisibleFields: () => boolean
  clearFieldValidation: (field: string) => void
  touchField: (field: string) => void
}

const props = defineProps({
  field: {
    type: String,
    default: '',
  },
  error: {
    type: String,
    required: false,
    default: '',
  },
  label: {
    type: String,
    required: false,
    default: '',
  },
  helperMessage: {
    type: String,
    required: false,
    default: '',
  },
  enableHelperMessage: {
    type: Boolean,
    required: false,
    default: true,
  },
})

const containerRef = ref<HTMLElement | null>(null)
const formValidation = inject<FormValidationContext | null>('formValidation', null)

const formInputConfig = inject<Ref<InputConfig> | null>('formInputConfig', null)

const requiredMark = computed(() => {
  if (!props.field || !formInputConfig?.value?.[props.field]) return false
  return hasRequiredValidation(formInputConfig.value[props.field]?.props?.validation as ValidationRule[])
})

const shouldShowValidationError = computed(() => {
  if (!formValidation || !props.field) return false
  return Boolean(formValidation.fieldTouched.value[props.field] || formValidation.submitAttempted.value)
})

const activeError = computed(() => {
  if (!formValidation || !props.field) return props.error
  if (!shouldShowValidationError.value) return ''
  return formValidation.fieldErrors.value[props.field] || ''
})

function onFocusOut(event: FocusEvent) {
  if (!formValidation || !props.field) return

  const relatedTarget = event.relatedTarget as Node | null
  const container = containerRef.value
  if (container && relatedTarget && container.contains(relatedTarget)) return

  formValidation.touchField(props.field)
}

function onValidationTouch() {
  if (!formValidation || !props.field) return
  formValidation.touchField(props.field)
}
</script>

<template>
  <div ref="containerRef" @focusout="onFocusOut" @validation:touch="onValidationTouch" :class="`${twMerge(`flex flex-col gap-2`, $attrs.class as string)}`">
    <div>
      <label v-if="props.label" class="text-sm font-medium">
        <template v-if="!$slots.label">
          {{ props.label }}
          <span v-if="requiredMark" class="text-error">*</span>
        </template>
        <slot v-else name="label"></slot>
      </label>
      <div v-if="enableHelperMessage && (helperMessage || activeError)">
        <label v-if="helperMessage && !activeError" class="text-sm text-on-surface/[67%]">{{ helperMessage }}</label>
        <label v-else :class="`text-sm text-error `">{{ activeError }}</label>
      </div>
    </div>
    <slot></slot>
  </div>
</template>

// apps/base-mobile/src/components/inputs/BaseInput.tsx
import type { ReactNode } from 'react'
import { useCallback, useMemo } from 'react'
import { Text, View, type StyleProp, type ViewStyle } from 'react-native'
import { useFormValidationContext } from '../composites/Form/form.context'
import { hasRequiredValidation, type ValidationRule } from '../composites/Form/validation'
import { materialColors } from '../../theme/material'

type BaseInputRenderProps = {
  activeError: string
  onValidationTouch: () => void
}

type BaseInputProps = {
  field?: string
  label?: string
  error?: string
  helperMessage?: string
  enableHelperMessage?: boolean
  onValidationTouch?: () => void
  containerStyle?: StyleProp<ViewStyle>
  children: ReactNode | ((props: BaseInputRenderProps) => ReactNode)
}

export function BaseInput({
  field = '',
  label = '',
  error = '',
  helperMessage = '',
  enableHelperMessage = false,
  onValidationTouch,
  containerStyle,
  children,
}: BaseInputProps) {
  const formValidation = useFormValidationContext()

  const requiredMark = useMemo(() => {
    if (!field || !formValidation?.inputConfig?.[field]) return false
    const validationRules = formValidation.inputConfig[field]?.props?.validation as ValidationRule[] | undefined
    return hasRequiredValidation(validationRules)
  }, [field, formValidation])

  const shouldShowValidationError = useMemo(() => {
    if (!formValidation || !field) return false
    return Boolean(formValidation.fieldTouched[field] || formValidation.submitAttempted)
  }, [field, formValidation])

  const activeError = useMemo(() => {
    if (!formValidation || !field) return error
    if (!shouldShowValidationError) return ''
    return formValidation.fieldErrors[field] || ''
  }, [error, field, formValidation, shouldShowValidationError])

  const handleValidationTouch = useCallback(() => {
    if (onValidationTouch) {
      onValidationTouch()
      return
    }

    if (!formValidation || !field) return
    formValidation.touchField(field)
  }, [field, formValidation, onValidationTouch])

  const content =
    typeof children === 'function'
      ? children({
          activeError,
          onValidationTouch: handleValidationTouch,
        })
      : children

  return (
    <View className="gap-1.5" style={containerStyle}>
      {label ? (
        <Text className="text-[13px] font-semibold" style={{ color: materialColors.onSurface }}>
          {label}
          {requiredMark ? <Text style={{ color: materialColors.error }}> *</Text> : null}
        </Text>
      ) : null}

      {content}

      {enableHelperMessage && (helperMessage || activeError) ? (
        <Text className="text-xs" style={{ color: activeError ? materialColors.error : materialColors.onSurfaceVariant }}>
          {activeError || helperMessage}
        </Text>
      ) : null}
    </View>
  )
}

export type { BaseInputProps, BaseInputRenderProps }
